#!/bin/bash

# v0.4
# (c) Maksim Mikhalchuk (maksim.mikhalchuk@gmail.com)

################################################################################
##### SOME STYLES ##############################################################
################################################################################
CBOLD="\e[1m"
CDIM="\e[2m"
CUNDER="\e[4m"
CBLINK="\e[5m"
CREVERSE="\e[7m"

CBLACK="\e[30m"
CRED="\e[31m"
CGREEN="\e[32m"
CYELLOW="\e[33m"
CBLUE="\e[34m"
CMAGENTA="\e[35m"
CCYAN="\e[36m"
CLGREY="\e[37m"
CDGREY="\e[90m"
CLRED="\e[91m"
CLGREEN="\e[92m"
CLYELLOW="\e[93m"
CLBLUE="\e[94m"
CLMAGENTA="\e[95m"
CLCYAN="\e[96m"
CWHITE="\e[97m"

CBBLACK="\e[40m"
CBRED="\e[41m"
CBGREEN="\e[42m"
CBYELLOW="\e[43m"
CBBLUE="\e[44m"
CBMAGENTA="\e[45m"
CBCYAN="\e[46m"
CBLGREY="\e[47m"
CBDGREY="\e[100m"
CBLRED="\e[101m"
CBLGREEN="\e[102m"
CBLYELLOW="\e[103m"
CBLBLUE="\e[104m"
CBLMAGENTA="\e[105m"
CBLCYAN="\e[106m"
CBWHITE="\e[107m"

CLR="\e[0m"
################################################################################

declare -A IP_ARR;

MY_NAME=`whoami`;
CHATLIST="/afs/ericpol.int/home/x/m/xmik/pub/chat.list";
PORT=45455
	# range:
	# TODO try ssh
OUTTYPE=0
	# 0 - normal
	# 1 - shouting
	# 2 - wispering
LINE_START="> ";

################################################################################
clear;
echo "Welcome to the Chat! Here are the users:"
# IP adress array
while IFS='' read -r IP_LINE || [[ -n "$IP_LINE" ]]; do
	addr=`echo $IP_LINE | awk '{print $1;}'`;
	usr=`echo $IP_LINE | awk '{print $2;}'`;
	IP_ARR[$usr]=$addr;
	echo -e $CGREEN$usr" "$CLGREY${IP_ARR[$usr]}$CLR;
done < "$CHATLIST";
MY_IP=${IP_ARR[$MY_NAME]};
echo "Say hello to everyone!"

# for i in "${!array[@]}"
# do
#   echo "key  : $i"
#   echo "value: ${array[$i]}"
# done

while true;
do
	echo -ne $LINE_START
	read TEXTLINE;
		# XXX Fix the arrow keys codes in the chat
	clear;
	
	case $TEXTLINE in
		"/w") #OUTTYPE=2
			echo -ne $CMAGENTA"wisper to ( "
			echo -ne ${!IP_ARR[@]}" ";
			echo -ne ") >"
			read TEXTLINE;
			echo;
			LINE_START=$CLMAGENTA"wisper to "$CUNDER"somebody"$CLR$CLMAGENTA"> "
			continue;;
		"/s") OUTTYPE=1
			LINE_START=$CRED$CDIM"SHOUT> "
			continue;;
		"/n") OUTTYPE=0
			LINE_START=$CLR"> "
			continue;;
		"")	continue;;
	esac
	

	# OUTPUT
	case $OUTTYPE in
		0)
			### NORMAL OUTPUT ###
			while IFS='' read -r IP_ADDR || [[ -n "$IP_ADDR" ]]; do
				echo -e $MY_NAME": "$TEXTLINE$CLR | nc "$IP_ADDR" $PORT;
			done < "$CHATLIST";;
			#####################
		1)
			### SHOUTING ###
			while IFS='' read -r IP_ADDR || [[ -n "$IP_ADDR" ]]; do
				echo -e $CRED$CDIM$MY_NAME$CBLINK$CRED" SHOUTING"$CLR": "$CRED$CDIM$TEXTLINE$CLR\
				| nc "$IP_ADDR" $PORT
			done < "$CHATLIST";;
			################
		2)
			### WISPERING ###
			while IFS='' read -r IP_ADDR || [[ -n "$IP_ADDR" ]]; do
				addr=`echo $IP_ADDR | awk '{print $1;}'`;
				usr=`echo $IP_ADDR | awk '{print $2;}'`;
				if [ $usr == $2 ]; then 
					# sent to user ### $CUNDER$CBOLD$usr$CLR
					echo -e $CLMAGENTA$MY_NAME\
						$CLMAGENTA"wispers"$CLR":"\
						$CLMAGENTA$TEXTLINE$CLR\
						| nc "$addr" $PORT
				fi 
				if [ $usr == $MY_NAME ]; then 
					# send to me
					echo -e $CLMAGENTA$MY_NAME\
						$CLMAGENTA"wispers to "$CLR$CLMAGENTA$CUNDER$2$CLR":"\
						$CLMAGENTA$TEXTLINE$CLR\
						| nc "$addr" $PORT
				fi
			done < "$CHATLIST";;
			#################
		*)
			# do nothing
			;;
	esac
	
	
	
	clear;
done
